name: Build and deploy Node.js app to Azure Web App - futnet-backend-sk123

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/futsnet-backend-sk123.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install and build in backend directory
        working-directory: ./backend
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment (backend only)
        run: |
          cd backend
          zip ../release.zip ./* -r
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Required for OIDC login

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "futnet-backend-sk123"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip
