# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - futnet-backend-sk123

on:
  push:
    branches:
      # !!! IMPORTANT: Change this to your main deployment branch, e.g., main or master !!!
      - main
    # Only trigger builds for changes within the backend directory
    paths:
      - 'backend/**'
      - '.github/workflows/futsnet-backend-sk123.yml' # Trigger if workflow itself changes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test in backend directory
        # Use working-directory to run these commands inside backend/
        working-directory: ./backend
        run: |
          npm install
          npm run build --if-present # Run build if your backend needs it (e.g., TypeScript)
          npm run test --if-present  # Run tests if you have them

      - name: Zip artifact for deployment (backend only)
        # Only zip the contents of the backend directory
        run: |
          cd backend
          zip ../release.zip ./* -r
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip # Upload the zip created from the backend directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for OIDC login
      # No contents: read needed here as checkout isn't performed

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          # Artifact is downloaded into the root of the runner workspace

      # No unzip step needed if deploying the zip directly

      - name: Login to Azure
        uses: azure/login@v2
        with:
          # These secret names should be automatically handled by Azure if User-assigned identity was set up correctly
          client-id: ${{ secrets.AZURE_CLIENT_ID }} # Standard name, check GitHub secrets if different
          tenant-id: ${{ secrets.AZURE_TENANT_ID }} # Standard name
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # Standard name

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'futnet-backend-sk123'
          slot-name: 'Production'
          package: release.zip # Deploy the zip artifact directly
